module record

import einar_hjortdal.firebird
import internal.common

// A password reset token is a password, it is generated by peony and lasts less than an hour.
pub struct PasswordResetToken {
pub:
	id                  common.ID
	password_hash       []u8
	password_salt       []u8
	password_details_id common.ID
	expires_at          firebird.DateTime
	created_at          firebird.DateTime
	updated_at          firebird.DateTime
	deleted_at          ?firebird.DateTime
}

pub fn (p PasswordResetToken) id() common.ID {
	return p.id
}

pub struct PasswordResetTokenCreateParams {
	id                  common.ID
	user_id             ?common.ID
	customer_id         ?common.ID
	password_hash       []u8
	password_salt       []u8
	password_details_id common.ID
}

pub fn password_reset_token_create(mut tx firebird.ClientTransaction, p PasswordResetTokenCreateParams) ! {
	if (p.user_id != none && p.customer_id != none) || (p.user_id == none && p.customer_id == none) {
		return error('A password reset token must belong to either a user or a customer')
	}

	mut c := []string{len: 0, cap: 5}
	mut params := []firebird.Value{len: 0, cap: 5, init: firebird.Null{}}

	c << 'id'
	params << p.id.bytes()

	if user_id := p.user_id {
		c << 'user_id'
		params << user_id.bytes()
	}

	if customer_id := p.customer_id {
		c << 'customer_id'
		params << customer_id.bytes()
	}

	c << 'password_hash'
	params << p.password_hash

	c << 'password_salt'
	params << p.password_salt

	c << 'password_details_id'
	params << p.password_details_id.bytes()

	tx.execute('INSERT INTO password_reset_token (${get_columns(c)}) VALUES (${get_placeholders(params)})',
		...params)!
}

pub struct UserPasswordResetToken {
	PasswordResetToken
pub:
	user_id common.ID
}

pub struct CustomerPasswordResetToken {
	PasswordResetToken
pub:
	customer_id common.ID
}
